# Generated by Django 5.0.7 on 2024-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handybot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default="unknown project", max_length=100),
        ),
        migrations.AddField(
            model_name="tool",
            name="tool_name",
            field=models.CharField(default="unknown tool", max_length=100),
        ),
    ]
